name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn dev
          wait-on: http://localhost:3000/
          config_file: browser
          spec: 'cypress/e2e/**/*'
        env:
          CYPRESS_baseUrl: http://localhost:3000/
